/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: wallon (https://sketchfab.com/realwallon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cartoon-car-09431a8df4344a84aa83a4095bef10fc
title: Cartoon Car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.body_car_body_0.geometry} material={materials.car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.hood_car_body_0.geometry} material={materials.car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.front_bumper_carbon_fiber_0.geometry} material={materials.carbon_fiber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.front_fenders_carbon_fiber_0.geometry} material={materials.carbon_fiber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane006_car_body_0.geometry} material={materials.car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane008_window_0.geometry} material={materials.window} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane009_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane007_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.trunk_car_body_0.geometry} material={materials.car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.black_parts_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.rear_fenders_carbon_fiber_0.geometry} material={materials.carbon_fiber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.headlight_glass_headlight_glass_0.geometry} material={materials.headlight_glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane026_chrome_0.geometry} material={materials.chrome} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.rear_bumper_carbon_fiber_0.geometry} material={materials.carbon_fiber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.exhaust_chrome_0.geometry} material={materials.chrome} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane005_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.side_skirts_carbon_fiber_0.geometry} material={materials.carbon_fiber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane011_window_0.geometry} material={materials.window} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane014_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane017_window_0.geometry} material={materials.window} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane033_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane034_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane035_window_0.geometry} material={materials.window} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane036_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.mirrors_chrome_0.geometry} material={materials.chrome} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.front_right_wheel_wheel_0.geometry} material={materials.wheel} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane038_black_parts_0.geometry} material={materials.black_parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.intercooler_intercooler_0.geometry} material={materials.intercooler} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.black_floats_Pure_black_0.geometry} material={materials.Pure_black} />
            <mesh geometry={nodes.black_floats_chrome_0.geometry} material={materials.chrome} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.rear_wheels_wheel_0.geometry} material={materials.wheel} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.front_left_wheel_wheel_0.geometry} material={materials.wheel} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
